dist: xenial
env:
  - DOCKER_COMPOSE_VERSION=1.17.1
services:
  - docker

before_install:
    - docker-compose up -d --build
#  - npm install eslint stylelint@8.2.0 stylelint-config-wikimedia

before_script:
    - docker-compose exec postgres psql wikilabels -U wikilabels -f /wikilabels/wikilabels/database/schema.sql
    - docker-compose exec postgres psql wikilabels -U wikilabels -f /wikilabels/wikilabels/database/schema-testdata.sql

script:
  - docker-compose exec wikilabels flake8 /wikilabels --ignore=E722,W504
    #  - timeout --preserve-status 8s wikilabels dev_server
#  - ./node_modules/.bin/eslint "wikilabels/wsgi/static/js/**/*.js"
#  - ./node_modules/.bin/stylelint "wikilabels/wsgi/static/css/*.css"
  - docker-compose exec wikilabels py.test --cov=wikilabels -m "not nottravis"

after_success:
  - codecov

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
