wikilabels:
  form_directory: forms/enabled
  form_i18n_directory: forms/i18n
  central_auth_host: https://meta.wikimedia.org
  maintenance_notice:
    date: OMG DATE
    url: https://foo.bar

wsgi:
  application_root: ""
  url_prefix: ""
  scheme: 'http'

database:
  host: localhost
  dbname: wikilabels

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
